set foreign_key_checks = 0;
create database wmarket;
create table wmarket.users (id int auto_increment primary key,name varchar(50),age int,address varchar(100),email varchar(50),number varchar(11),password tinyblob,province int,image varchar(50),valid int default 1,active timestamp default current_timestamp on update current_timestamp,foreign key(province) references wmarket.provinces(id));
create table wmarket.orders (id int auto_increment primary key,pid int,buyer int,state int);
create table wmarket.assets (id int auto_increment primary key,tobuy varchar(2000),tosell varchar(2000),toship varchar(2000),totake varchar(2000));
create table wmarket.categories (id int auto_increment primary key,name char(50));
create table wmarket.products (id int auto_increment primary key,name varchar(50),description varchar(200),image varchar(50),buy_price float,sell_price float,category int,brand varchar(20),cond int,rating int default 0,sold int default 0,payment int,transport int,sale float default 0,quantity int,shopid int,province int,foreign key(category) references wmarket.categories(id),foreign key(shopid) references wmarket.users(id)) ;
create table wmarket.balances (id int auto_increment primary key,sold int default 0,revenue float default 0,profit float default 0,debt float default 0);
create table wmarket.provinces (id int auto_increment primary key,name varchar(20),weight int);

insert into wmarket.provinces (name,weight) values ('Sơn La',3);
insert into wmarket.provinces (name,weight) values ('Lai Châu',3);
insert into wmarket.provinces (name,weight) values ('Lào Cai',3);
insert into wmarket.provinces (name,weight) values ('Cao Bằng',3);
insert into wmarket.provinces (name,weight) values ('Lạng Sơn',2);
insert into wmarket.provinces (name,weight) values ('Quảng Ninh',2);
insert into wmarket.provinces (name,weight) values ('Phú Thọ',2);
insert into wmarket.provinces (name,weight) values ('Tuyên Quang',2);
insert into wmarket.provinces (name,weight) values ('Thái Nguyên',2);
insert into wmarket.provinces (name,weight) values ('Hải Phòng',2);
insert into wmarket.provinces (name,weight) values ('Bắc Ninh',1);
insert into wmarket.provinces (name,weight) values ('Hà Nội',2);
insert into wmarket.provinces (name,weight) values ('Hưng Yên',1);
insert into wmarket.provinces (name,weight) values ('Ninh Bình',2);
insert into wmarket.provinces (name,weight) values ('Thanh Hóa',2);
insert into wmarket.provinces (name,weight) values ('Nghệ An',2);
insert into wmarket.provinces (name,weight) values ('Hà Tĩnh',2);
insert into wmarket.provinces (name,weight) values ('Quảng Trị',2);
insert into wmarket.provinces (name,weight) values ('Huế',1);
insert into wmarket.provinces (name,weight) values ('Đà Nẵng',1);
insert into wmarket.provinces (name,weight) values ('Bình Định',2);
insert into wmarket.provinces (name,weight) values ('Phú Yên',2);
insert into wmarket.provinces (name,weight) values ('Khánh Hòa',2);
insert into wmarket.provinces (name,weight) values ('Gia Lai',1);
insert into wmarket.provinces (name,weight) values ('Đắk Lắk',1);
insert into wmarket.provinces (name,weight) values ('Đắk Nông',1);
insert into wmarket.provinces (name,weight) values ('Ninh Thuận',1);
insert into wmarket.provinces (name,weight) values ('Bà Rịa - Vũng Tàu',1);
insert into wmarket.provinces (name,weight) values ('Bình Dương',1);
insert into wmarket.provinces (name,weight) values ('Hồ Chí Minh',1);
insert into wmarket.provinces (name,weight) values ('Vĩnh Long',2);
insert into wmarket.provinces (name,weight) values ('An Giang',2);
insert into wmarket.provinces (name,weight) values ('Cần Thơ',2);
insert into wmarket.provinces (name,weight) values ('Cà Mau',1);

insert into wmarket.categories (name) values ('Thực phẩm');
insert into wmarket.categories (name) values ('Thuốc');
insert into wmarket.categories (name) values ('Đồ gia dụng');
insert into wmarket.categories (name) values ('Đồ điện tử');
insert into wmarket.categories (name) values ('Đồ kim khí');
insert into wmarket.categories (name) values ('Phụ tùng');
insert into wmarket.categories (name) values ('Đồ bếp');
insert into wmarket.categories (name) values ('Đồ chơi');
insert into wmarket.categories (name) values ('Quần áo');
insert into wmarket.categories (name) values ('Mỹ phẩm');
insert into wmarket.categories (name) values ('Trang sức');
insert into wmarket.categories (name) values ('Nước hoa');
insert into wmarket.categories (name) values ('Nhạc cụ');